DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS sentence;

CREATE TABLE user (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL
);

CREATE TABLE sentence (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    speaker TEXT NOT NULL,
    content TEXT NOT NULL,
    isGenerated BOOLEAN,
    input_by TEXT
);
